language: csharp
mono: none
dotnet: 2.1.300
script:
 - dotnet restore
 - dotnet test App.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutputDirectory=coverage
 - dotnet run --project=App.tests codecov -- -f ./coverage/coverage.xml -verbose
after_success:
 - bash <(curl -s https://codecov.io/bash)